### ISSUE TITLE
Gitea keycloak_sso role HTTP calls can fail if Cert is not ready

### ISSUE THREAD

**Issue by rmccright-ms3** [MS3Inc/tavros#46]
Add retry strategy base on others at 30s delay between calls, and 30s retries for a 15 min effective wait.

**Comment by jam01** [comment]
@rmccright-ms3 think this is fixed, right?

**Comment by rmccright-ms3** [comment]
Sure is, just double-checked.
https://github.com/MS3Inc/tavros/blob/main/roles/gitea/tasks/keycloak_sso.yaml#L15
