### ISSUE TITLE
resolve issue with nexus artifacts when keycloak is enabled

### ISSUE THREAD

**Issue by rlratcliffe** [MS3Inc/tavros#96]
we have a camel-web-service which is using a dependency that is deployed to maven-snaphots in nexus in our tavros cluster. keycloak was temporarily turned off to deploy it. the pipelines however fail to build the web-service or the dependency when keycloak is enabled.

two scenarios that are known so far, which **don't** succeed if keycloak is enabled for nexus:
- if a custom pipeline exists to `mvn deploy` a java snapshot dependency to artifacts (not a camel web service/docker image)
- if a camel web service uses a snapshot dependency from artifacts that needs to be pulled during its pipeline

both scenarios use a custom settings.xml and `repository` element/`distributionManagement `element in pom pointing to https://artifacts.fqdn/repository/maven-snapshots. without keycloak both scenarios work.

**Comment by rlratcliffe** [comment]
camel web service has a settings.xml with:

```
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
    <servers>
        <server>
            <id>theid</id>
            <username>thenexususername</username>
            <password>thenexuspassword</password>
        </server>
    </servers>
</settings>
```
and this in the pom:

```
    <repositories>
        <repository>
            <releases>
                <enabled>false</enabled>
                <updatePolicy>always</updatePolicy>
                <checksumPolicy>warn</checksumPolicy>
            </releases>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>never</updatePolicy>
                <checksumPolicy>fail</checksumPolicy>
            </snapshots>
            <id>theid</id>
            <name>maven</name>
            <url>https://artifacts.fqdn/repository/maven-snapshots/</url>
            <layout>default</layout>
        </repository>
    </repositories>
```

the dependency we created that the api is using has the same settings.xml as above

and the pom has
```
    <distributionManagement>
        <repository>
            <id>theid</id>
            <name>releases</name>
            <url>https://artifacts.fqdn/repository/maven-releases/</url>
        </repository>
        <snapshotRepository>
            <id>theid</id>
            <name>snapshots</name>
            <url>https://artifacts.fqdn/repository/maven-snapshots/</url>
        </snapshotRepository>
    </distributionManagement>
```

when it fails it fails because it's hitting the keycloak page (this css mentioned matches the keycloak page). happens with both maven-deploy-plugin:3.0.0-M1:deploy and maven-deploy-plugin:2.7:deploy.

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project <redacted>: Failed to update metadata <redacted>/maven-metadata.xml: Could not parse metadata <redacted>/maven-metadata-nexus.xml: end tag name </head> must be the same as start tag <meta> from line 7 (position: TEXT seen .../login/keycloak/css/tile.css" rel="stylesheet" />\n</head>... @20:8)`

there isn't an issue related to the settings/pom as these work effectively without keycloak. this information is merely provided as a reproducer.

**Comment by rlratcliffe** [comment]
@jam01

**Comment by jam01** [comment]
Need to use the nosso Kong ingress

**Comment by jam01** [comment]
https://github.com/MS3Inc/tavros/blob/main/tests/integration/targets/playbooks/provision_playbook/example.com/platform/nexus/default/ingress-buildtools.yaml#L18

**Comment by jam01** [comment]
Yes there's a jenkins ci user that should be used 
https://github.com/MS3Inc/tavros/blob/main/roles/jenkins/templates/keycloakuser-jenkins-ci.j2#L20

**Comment by rlratcliffe** [comment]
I am working on implementing this in our cluster, so if there's interest, will look into making a PR when I get it working so the functionality is available to others. currently looking into using a config map for the settings.xml so it doesn't need to be repeated in all of the repos.

**Comment by rmccright-ms3** [comment]
Shouldn't cred reference via ENV var be added to poms via Archetype?

**Comment by rlratcliffe** [comment]
it can't, it has to be an id that's referenced in the settings.xml as far as I'm aware for [distributionManagement and respositores.](https://maven.apache.org/pom.html#Repositories)

but I just realized that the plan was already to have a settings.xml in the archetype for this [PR](https://github.com/MS3Inc/camel-archetypes/pull/26) so if we're fine with settings.xml being included in the archetype then it should be fine for this approach too. was just looking for a way to reduce duplication of it since the settings.xml will mostly only be used inside of the cluster afaik.

**Comment by jam01** [comment]
Yeah, I can see some orgs not wanting to have a .settings.xml in each repo but instead centralize it through a config map or secret. Maybe we make it an option on the archetype to accommodate both ways

-------- Original Message --------

**Comment by jam01** [comment]
Good to close @rlratcliffe ?

**Comment by jam01** [comment]
going to close for now @rlratcliffe, please re-open if we need to

**Comment by rlratcliffe** [comment]
sorry for the delay. plan to make a PR at some point for changes to the archetype and tavros to make this a little easier, but don't think the issue necessarily needs to be open for that.
